import = ["~/.config/alacritty/themes/themes/tokyo-night.toml"]

[window]
opacity = 0.95
resize_increments = true

[window.padding]
x = 0
y = 0

[font]
size = 12.0

[font.normal]
family = "HackGenConsole Nerd Font"
style = "Regular"

[font.bold]
family = "HackGenConsole Nerd Font"
style = "Bold"

[font.italic]
family = "HackGenConsole Nerd Font"
style = "Italic"

[font.bold_italic]
family = "HackGenConsole Nerd Font"
style = "Bold Italic"

[font.offset]
x = 0
y = 0

[keyboard]
bindings = [
  { key = "F11", action = "ToggleFullscreen" },
  { key = "N", mods = "Control|Shift", action = "SpawnNewInstance" },
]

